name: Jest Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Codebase
      - uses: actions/checkout@v1
        # Set Node Version
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

        # Get Cached Dependencies if Existing
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

        # Caching of Dependencies
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}:loki-testing

        # Install Dependencies if not Cached
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --silent

        # Run Jest Tests & Generate Coverage Report
      - name: Run Tests With Coverage
        run: yarn test:cov
